#!/usr/bin/env python3
"""Script to update defaultEquipment in explore/page.tsx with corrected emojis and detailed descriptions."""

import re

FILE_PATH = '../src/app/student/explore/page.tsx'

NEW_EQUIPMENT = '''const defaultEquipment: Equipment[] = [
  // หมวดที่ 1 อุปกรณ์เครื่องใช้บนโต๊ะอาหาร (Tableware)
  { name: 'จานอาหารหลัก', nameEn: 'Dinner Plate', emoji: '🍽️', use: 'จานขนาดใหญ่ เส้นผ่านศูนย์กลาง 27–30 ซม. สำหรับเสิร์ฟอาหารจานหลัก (Main Course) วางไว้ตรงกลางหน้าผู้รับบริการ ห่างจากขอบโต๊ะ 2 ซม. ต้องอุ่นจานก่อนเสิร์ฟอาหารร้อนทุกครั้ง', sentence: 'The dinner plate is placed at the center of the cover for serving the main course — warm it before use.' },
  { name: 'จานสลัด', nameEn: 'Salad Plate', emoji: '🥗', use: 'จานขนาดกลาง เส้นผ่านศูนย์กลาง 19–22 ซม. สำหรับเสิร์ฟสลัดหรืออาหารเรียกน้ำย่อย (Appetizer) วางไว้ด้านบนซ้ายของจานอาหารหลัก หรือเอาออกก่อนเสิร์ฟจานหลัก', sentence: 'The salad plate is served to the left of the cover for appetizers or salads before the main course.' },
  { name: 'จานขนมปัง', nameEn: 'Bread Plate', emoji: '🍞', use: 'จานขนาดเล็ก เส้นผ่านศูนย์กลาง 15–17 ซม. วางด้านซ้ายมือของผู้รับบริการ เหนือส้อมอาหารหลัก ใช้วางขนมปัง เนย และทาร์ตตลอดมื้ออาหาร มีดเนยวางพาดบนจานด้านขวา', sentence: 'The bread plate is placed to the upper left of the cover, above the dinner fork, with the butter knife across it.' },
  { name: 'จานรองถ้วยชา', nameEn: 'Saucer', emoji: '🫗', use: 'จานรองขนาดเล็กสำหรับวางถ้วยชาหรือถ้วยกาแฟ ช่วยรับหยดน้ำและรักษาความสะอาดโต๊ะ วางพร้อมกับถ้วยเสมอ ช้อนชาวางบนจานรองด้านขวา หูถ้วยหันขวาเสมอ', sentence: 'The saucer always pairs with a cup — place the teaspoon on the right side and position the cup handle at 4 o\'clock.' },
  { name: 'ถ้วยซุป', nameEn: 'Soup Bowl', emoji: '🥣', use: 'ถ้วยขนาดกลางมีสองหูจับ สำหรับเสิร์ฟซุปร้อน วางบนจานรองซุป (Underliner) เสิร์ฟจากด้านขวาของผู้รับบริการ ต้องอุ่นถ้วยก่อนเสิร์ฟ ช้อนซุปวางด้านขวาของจาน', sentence: 'The soup bowl is pre-warmed and served from the right side of the guest on an underliner plate.' },
  { name: 'ถ้วยกาแฟ', nameEn: 'Coffee Cup', emoji: '☕', use: 'ถ้วยเซรามิคสำหรับบริการกาแฟร้อน ขนาด 6–8 ออนซ์ วางบนจานรอง หูถ้วยหันขวา เสิร์ฟหลังอาหารหลักหรือพร้อมของหวาน อุณหภูมิเสิร์ฟ 85–90°C ไม่เติมกาแฟเกิน 3/4 ถ้วย', sentence: 'The coffee cup is served after the main course at 85–90°C with the handle at 4 o\'clock on the saucer.' },
  { name: 'ถ้วยชา', nameEn: 'Tea Cup', emoji: '🍵', use: 'ถ้วยบางเบาสำหรับบริการชาร้อน เล็กกว่าถ้วยกาแฟเล็กน้อย วางบนจานรอง หูถ้วยหันขวา เสิร์ฟพร้อมน้ำตาลและนม ชุดชาประกอบด้วย ถ้วยชา จานรอง ช้อนชา และกาน้ำชา', sentence: 'The tea cup is placed on a saucer with a teaspoon; serve tea from the teapot and offer sugar and milk separately.' },
  { name: 'ชามของหวาน', nameEn: 'Dessert Bowl', emoji: '🍨', use: 'ชามขนาดกลางสำหรับเสิร์ฟของหวาน เช่น ไอศกรีม ผลไม้ พุดดิ้ง หรือมูส วางบน Underliner เสิร์ฟพร้อมช้อนของหวาน ควรแช่เย็นก่อนใส่ไอศกรีมเพื่อไม่ให้ละลายเร็ว', sentence: 'Chill the dessert bowl before serving ice cream — present with a dessert spoon on an underliner plate.' },
  { name: 'ถ้วยน้ำจิ้ม', nameEn: 'Sauce Dish', emoji: '🫙', use: 'จานหรือถ้วยขนาดเล็กสำหรับใส่น้ำจิ้ม ซอสราด หรือเครื่องปรุงเพิ่มเติม วางไว้ข้างจานหลักด้านขวา ในร้านอาหารไทยมักเสิร์ฟพร้อมอาหารทอดหรืออาหารทะเล', sentence: 'The sauce dish holds dipping sauces or condiments and is placed to the upper right of the main plate.' },

  // หมวดที่ 2 เครื่องเงินและช้อนส้อม (Flatware / Cutlery)
  { name: 'มีดอาหารหลัก', nameEn: 'Dinner Knife', emoji: '🗡️', use: 'มีดขนาดใหญ่ที่สุดในชุด ใบมีดหันเข้าหาจาน วางไว้ด้านขวาของจานอาหารหลัก ใช้ตัดและแล่อาหารจานหลัก เช่น เนื้อสเต็ก ปลา ไก่ ต้องขัดเงาก่อนวางตั้งโต๊ะเสมอ', sentence: 'The dinner knife is placed to the right of the plate with the blade facing inward — polish before setting.' },
  { name: 'ส้อมอาหารหลัก', nameEn: 'Dinner Fork', emoji: '🍴', use: 'ส้อมขนาดใหญ่ที่สุดในชุด 4 ง่าม วางด้านซ้ายของจานอาหารหลัก ใช้รับประทานอาหารจานหลักทุกชนิด เป็นอุปกรณ์ที่ใช้บ่อยที่สุดในชุดช้อนส้อม ขัดเงาก่อนตั้งโต๊ะ', sentence: 'The dinner fork is the largest fork, placed to the left of the plate — it is used for the entire main course.' },
  { name: 'ช้อนอาหาร', nameEn: 'Dinner Spoon', emoji: '🥄', use: 'ช้อนขนาดใหญ่รูปทรงรีสำหรับรับประทานอาหาร เช่น ข้าว กับข้าวไทย หรือพาสต้า วางด้านขวาของมีดอาหาร ในโต๊ะสากลมักไม่ใช้ แต่ในร้านอาหารไทยถือเป็นอุปกรณ์หลัก', sentence: 'The dinner spoon is essential in Thai-style service and is placed to the right of the dinner knife.' },
  { name: 'ช้อนซุป', nameEn: 'Soup Spoon', emoji: '🥣', use: 'ช้อนหัวกลมใหญ่กว่าช้อนอาหาร ใช้ตักซุปและน้ำซุป วิธีใช้ที่ถูกต้อง: ตักออกจากตัวไปทางนอก (away from body) แล้วดื่มจากด้านข้างช้อน ห้ามดูดเสียงดัง ไม่ใส่ช้อนทั้งอันในปาก', sentence: 'Use the soup spoon by scooping away from yourself and sipping quietly from the side — never slurp.' },
  { name: 'มีดเนย', nameEn: 'Butter Knife', emoji: '🧈', use: 'มีดใบสั้นไม่มีคม ปลายมนกว้าง วางบนจานขนมปังด้านขวาหรือพาดขวางจาน ใช้ตักและทาเนยบนขนมปังเท่านั้น ห้ามตัดขนมปัง ควรหักขนมปังด้วยมือก่อนแล้วจึงทาเนย', sentence: 'Use the butter knife only for spreading — tear bread by hand first, then spread butter on each small piece.' },
  { name: 'ส้อมสลัด', nameEn: 'Salad Fork', emoji: '🥗', use: 'ส้อม 4 ง่ามขนาดเล็กกว่าส้อมอาหารหลัก วางด้านซ้ายนอกสุดถัดจากส้อมอาหารหลัก ใช้รับประทานสลัดและอาหารเรียกน้ำย่อย เก็บออกพร้อมจานสลัดก่อนเสิร์ฟจานหลัก', sentence: 'The salad fork is smaller than the dinner fork and placed to the outer left — remove it with the salad plate.' },
  { name: 'มีดปลา', nameEn: 'Fish Knife', emoji: '🐟', use: 'มีดรูปทรงพิเศษใบกว้างปลายมน ไม่คม ออกแบบเพื่อยกเนื้อปลาออกจากก้างโดยไม่ทำลายเนื้อ วางด้านขวาถัดจากมีดอาหารหลัก ใช้คู่กับส้อมปลา นิยมใช้ในคอร์สปลาโดยเฉพาะ', sentence: 'The fish knife has a wide blunt blade — use it to lift fish flesh from bones without crushing the fillet.' },
  { name: 'ส้อมปลา', nameEn: 'Fish Fork', emoji: '🐠', use: 'ส้อม 4 ง่ามรูปทรงพิเศษ ง่ามนอกด้านซ้ายกว้างกว่าปกติ ใช้จับและแยกเนื้อปลาออกจากก้าง วางด้านซ้ายถัดในจากส้อมสลัด ใช้พร้อมมีดปลาสำหรับคอร์สปลาโดยเฉพาะ', sentence: 'The fish fork has a wider outer tine for separating fish flesh — always use it with the fish knife.' },
  { name: 'ช้อนของหวาน', nameEn: 'Dessert Spoon', emoji: '🍨', use: 'ช้อนขนาดกลางระหว่างช้อนซุปกับช้อนชา วางเหนือจานอาหารขนานกัน ด้ามชี้ขวา ใช้รับประทานของหวานที่มีน้ำ เช่น พุดดิ้ง ไอศกรีมในซอส มูส ปานาคอตต้า', sentence: 'The dessert spoon is placed horizontally above the plate with the handle pointing right — for liquid desserts.' },
  { name: 'ส้อมของหวาน', nameEn: 'Dessert Fork', emoji: '🍰', use: 'ส้อม 3 ง่ามขนาดเล็ก วางเหนือจานอาหารขนานกัน ด้ามชี้ซ้าย (คู่กับช้อนของหวาน) ใช้รับประทานของหวานแห้ง เช่น เค้ก ทาร์ต พาย หรือผลไม้สด', sentence: 'The dessert fork is placed horizontally above the plate with the handle facing left — for solid desserts and cake.' },
  { name: 'ช้อนชา', nameEn: 'Tea Spoon', emoji: '🍵', use: 'ช้อนขนาดเล็กสำหรับคนชาและน้ำตาล วางบนจานรองถ้วยชา ด้านขวาของถ้วย หลังคนน้ำตาลแล้วต้องวางช้อนบนจานรอง ห้ามทิ้งไว้ในถ้วย ยังใช้ตวงส่วนผสมในการทำอาหารได้', sentence: 'After stirring with the teaspoon, rest it on the right side of the saucer — never leave it standing in the cup.' },
  { name: 'ช้อนกาแฟ', nameEn: 'Coffee Spoon', emoji: '☕', use: 'ช้อนขนาดเล็กที่สุดในชุด เล็กกว่าช้อนชาเล็กน้อย ออกแบบมาสำหรับถ้วยเอสเปรสโซขนาดเล็ก (Demitasse) ใช้คนน้ำตาลในกาแฟเข้มข้น วางบนจานรองด้านขวา', sentence: 'The coffee spoon is the smallest in the set — designed for stirring sugar in a small demitasse espresso cup.' },

  // หมวดที่ 3 เครื่องแก้ว (Glassware)
  { name: 'แก้วน้ำเปล่า', nameEn: 'Water Goblet', emoji: '🫗', use: 'แก้วทรงถ้วยก้านใหญ่ ความจุ 10–12 ออนซ์ วางเหนือมีดอาหารหลักด้านขวาบน ใช้บริการน้ำเปล่า หรือน้ำดื่มตลอดมื้อ คอยเติมน้ำเมื่อเหลือ 1 ใน 3 เสมอ', sentence: 'The water goblet is placed at the tip of the dinner knife — refill it when it reaches one-third full.' },
  { name: 'แก้วไวน์แดง', nameEn: 'Red Wine Glass', emoji: '🍷', use: 'แก้วก้านทรงกลมป่องใหญ่ ความจุ 12–16 ออนซ์ ทรงกลมช่วยให้ไวน์แดงสัมผัสอากาศและระเหยกลิ่นได้ดี เติมไวน์เพียง 1/3 ของแก้ว จับที่ก้านแก้วเสมอ ไม่จับที่ตัวถ้วย', sentence: 'Red wine glass has a large bowl for breathing — fill only one-third and hold by the stem, never the bowl.' },
  { name: 'แก้วไวน์ขาว', nameEn: 'White Wine Glass', emoji: '🥂', use: 'แก้วก้านทรงรี ปากแคบกว่าแก้วไวน์แดง ความจุ 8–12 ออนซ์ ทรงแคบช่วยรักษาอุณหภูมิเย็นให้นานขึ้น เติมไวน์ 2/3 ของแก้ว เสิร์ฟที่อุณหภูมิ 8–12°C', sentence: 'White wine glass has a narrower bowl to keep the wine chilled — fill two-thirds and serve at 8–12°C.' },
  { name: 'แก้วแชมเปญ', nameEn: 'Champagne Flute', emoji: '🥂', use: 'แก้วก้านทรงยาวแคว ความจุ 6–8 ออนซ์ ทรงยาวช่วยให้ฟอง (Bubbles) ลอยขึ้นได้นานและสวยงาม เติมแชมเปญ 3/4 ของแก้ว เสิร์ฟแบบเย็นจัดที่ 4–8°C', sentence: 'Champagne flute preserves carbonation — fill three-quarters and serve chilled at 4–8°C.' },
  { name: 'แก้วค็อกเทล', nameEn: 'Cocktail Glass', emoji: '🍸', use: 'แก้วทรง V รูปสามเหลี่ยม ความจุ 4–6 ออนซ์ ไม่มีน้ำแข็ง (Straight Up) ก้านยาวป้องกันความร้อนจากมือทำให้เครื่องดื่มอุ่น ใช้เสิร์ฟ Martini Manhattan Cosmopolitan', sentence: 'Cocktail glass is the classic V-shaped vessel for straight-up cocktails — hold by the stem to keep it chilled.' },
  { name: 'แก้วไฮบอล', nameEn: 'Highball Glass', emoji: '🥤', use: 'แก้วทรงตรงสูง ความจุ 8–12 ออนซ์ สำหรับเครื่องดื่มผสมที่มีน้ำอัดลม เช่น Gin & Tonic Whisky Soda หรือน้ำผลไม้ เติมน้ำแข็งก่อนแล้วจึงเทเครื่องดื่มลงทีหลัง', sentence: 'Highball glass is used for long drinks with mixers — add ice first, then pour the spirit and mixer.' },
  { name: 'แก้วร็อกส์', nameEn: 'Rocks Glass', emoji: '🥃', use: 'แก้วทรงกว้างเตี้ย ความจุ 6–8 ออนซ์ เรียกอีกชื่อว่า Old-Fashioned Glass ใช้บริการวิสกี้ บรั่นดี รัม หรือสก็อตช์ที่เสิร์ฟพร้อมน้ำแข็ง (On the Rocks) หรือเปล่า (Neat)', sentence: 'Rocks glass is used for spirits served neat or on the rocks — also called old-fashioned glass.' },
  { name: 'แก้วเบียร์', nameEn: 'Beer Glass', emoji: '🍺', use: 'แก้วทรงตรงปากบาน ความจุ 10–16 ออนซ์ เทเบียร์ลงแก้วทำมุม 45 องศาก่อน แล้วค่อยตั้งตรงเพื่อให้ฟองพอดี 1–2 ซม. ล้างแก้วด้วยน้ำเย็นก่อนรินเบียร์เสมอ', sentence: 'Pour beer at 45° first, then straighten to achieve a perfect 1–2 cm foam head — rinse the glass with cold water first.' },
  { name: 'แก้วบรั่นดี', nameEn: 'Brandy Snifter', emoji: '🍶', use: 'แก้วทรงลูกแพร์ก้านสั้น ความจุ 8–12 ออนซ์ ออกแบบให้กุมด้วยมือทั้งสองข้างเพื่อถ่ายความร้อนจากฝ่ามือ ทำให้บรั่นดีระเหยสารหอม เทบรั่นดีเพียง 1–2 ออนซ์', sentence: 'Cup the brandy snifter in both palms to gently warm the spirit and release its complex aromas.' },
  { name: 'แก้วมาร์ตินี', nameEn: 'Martini Glass', emoji: '🍸', use: 'แก้วทรง V ก้านยาว ความจุ 3–5 ออนซ์ ต้องแช่แก้วในช่องแช่แข็งก่อนเสิร์ฟ จับที่ก้านเท่านั้น ตกแต่งด้วยมะกอกหรือเปลือกมะนาว เสิร์ฟแบบ Straight Up ไม่มีน้ำแข็ง', sentence: 'Chill the martini glass before service — hold only by the stem and garnish with an olive or lemon twist.' },

  // หมวดที่ 4 เครื่องลินิน (Linen)
  { name: 'ผ้าปูโต๊ะ', nameEn: 'Table Cloth', emoji: '🟫', use: 'ผ้าปูโต๊ะสีขาวหรือสีตามธีมร้าน ต้องสะอาด รีดเรียบไม่มีรอยย่น ปูให้ตกเท่ากันทุกด้าน ประมาณ 25–30 ซม. ล้างทำความสะอาดและเปลี่ยนทุกรอบหลังแขกกลับ', sentence: 'The table cloth must be clean, wrinkle-free, and hang evenly 25–30 cm on all sides of the table.' },
  { name: 'ผ้ารองโต๊ะ', nameEn: 'Under Cloth', emoji: '⬛', use: 'ผ้าหนาหรือแผ่นยาง วางใต้ผ้าปูโต๊ะก่อนเสมอ ช่วยลดเสียงการวางจานช้อนส้อม ป้องกันผ้าปูโต๊ะเลื่อนหลุด และปกป้องพื้นผิวโต๊ะจากรอยขีดข่วน', sentence: 'Under cloth is placed beneath the tablecloth to absorb noise, prevent slipping, and protect the table surface.' },
  { name: 'ผ้าเช็ดปาก', nameEn: 'Napkin', emoji: '🎗️', use: 'ผ้าสี่เหลี่ยม 45×45 ซม. พับเป็นรูปทรงต่างๆ วางบนจานอาหารหรือด้านซ้ายมือ ผู้รับบริการใช้วางบนตักและเช็ดปาก ห้ามใช้เช็ดโต๊ะหรืออุปกรณ์ เปลี่ยนทุกรอบบริการ', sentence: 'The napkin is folded and placed on the center plate or left side — guests place it on their lap during dining.' },
  { name: 'ผ้าคลุมถาด', nameEn: 'Tray Cloth', emoji: '🧻', use: 'ผ้าสำหรับปูบนถาดเสิร์ฟ ช่วยกันลื่นของอุปกรณ์บนถาด รักษาความสะอาด และป้องกันเสียงดัง มักทำจากผ้าฝ้ายหรือผ้าลินินสีขาว ต้องเปลี่ยนทุกครั้งที่ใช้งาน', sentence: 'A tray cloth prevents glasses and dishes from sliding during transport — change it after every use.' },
  { name: 'ผ้าเช็ดแก้ว', nameEn: 'Glass Cloth', emoji: '🧺', use: 'ผ้าสะอาดไม่มีขนฝุ่น (Lint-Free) สำหรับเช็ดและขัดเงาแก้ว วิธีใช้: จับที่ก้านด้วยผ้า หมุนเช็ดด้านในและด้านนอก ส่องไฟตรวจรอยน้ำก่อนนำขึ้นโต๊ะเสมอ', sentence: 'Hold the glass by the stem with the cloth, polish inside and out, then check against the light for watermarks.' },
  { name: 'ผ้าเช็ดเครื่องเงิน', nameEn: 'Polishing Cloth', emoji: '✨', use: 'ผ้านุ่มสำหรับขัดเงาช้อนส้อมและเครื่องเงิน ขัดให้สะอาดหมดรอยน้ำและลายนิ้วมือ วิธีใช้: อุ่นน้ำใส่ผ้าแล้วเช็ด จากนั้นใช้ผ้าแห้งขัดให้เงา ตรวจก่อนตั้งโต๊ะทุกครั้ง', sentence: 'Polish flatware with the cloth by holding the handle — check for watermarks and fingerprints before setting the table.' },

  // หมวดที่ 5 อุปกรณ์เครื่องปรุง (Condiment Set)
  { name: 'ขวดเกลือ', nameEn: 'Salt Shaker', emoji: '🧂', use: 'ภาชนะมีฝาเจาะรูเล็กๆ บรรจุเกลือป่น สำหรับปรุงรสอาหารด้วยตนเอง วางคู่กับขวดพริกไทยเสมอ ใส่เมล็ดข้าว 1–2 เม็ดดูดความชื้น เปลี่ยนเติมเกลือและล้างขวดทุกสัปดาห์', sentence: 'Salt and pepper shakers are always paired together — add rice grains to absorb moisture and prevent clumping.' },
  { name: 'ขวดพริกไทย', nameEn: 'Pepper Shaker', emoji: '🫙', use: 'ภาชนะมีฝาเจาะรูเล็กๆ บรรจุพริกไทยป่น วางคู่กับขวดเกลือ เขย่าเบาๆ ขณะโรยพริกไทย ระวังโรยมากเกินไป สะอาดและตรวจสอบปริมาณก่อนเปิดบริการทุกวัน', sentence: 'Pepper shaker is always paired with the salt shaker — check fill level and clean the holes before each service.' },
  { name: 'โถน้ำตาล', nameEn: 'Sugar Bowl', emoji: '🍯', use: 'โถมีฝาปิดหรือแบบเปิด บรรจุน้ำตาลขาว น้ำตาลดิบ หรือซองน้ำตาล เสิร์ฟพร้อมชุดชาและกาแฟ ใช้คีมน้ำตาลสำหรับน้ำตาลก้อน ต้องสะอาดและเติมก่อนบริการ', sentence: 'Sugar bowl accompanies tea or coffee service — use a sugar tong for cubes and keep it filled before service.' },
  { name: 'ขวดซอส', nameEn: 'Sauce Bottle', emoji: '🫙', use: 'ขวดแก้วหรือพลาสติกบรรจุซอสปรุงรส เช่น ซอสพริก ซอสมะเขือเทศ ซอสถั่วเหลือง ต้องสะอาด ฝาแน่น ป้ายระบุชัดเจน เช็ดทำความสะอาดรอบขวดก่อนตั้งโต๊ะทุกวัน', sentence: 'Sauce bottles must be clean, labeled, and drip-free — wipe the exterior thoroughly before placing on the table.' },
  { name: 'ขวดน้ำส้มสายชู', nameEn: 'Vinegar Bottle', emoji: '🏺', use: 'ขวดแก้วใสบรรจุน้ำส้มสายชูสำหรับปรุงรสสลัดหรืออาหาร วางในชุดเครื่องปรุงคู่กับน้ำมันมะกอก ต้องระบุฉลากชัดเจนและสะอาดทุกครั้ง เปลี่ยนทุกสัปดาห์', sentence: 'Vinegar bottle is paired with olive oil as a salad dressing set — label clearly, clean daily, and refill weekly.' },
  { name: 'ขวดน้ำมันมะกอก', nameEn: 'Olive Oil Bottle', emoji: '🫒', use: 'ขวดแก้วบรรจุน้ำมันมะกอก Extra Virgin เสิร์ฟคู่กับน้ำส้มสายชูสำหรับจิ้มขนมปัง ทำน้ำสลัด หรือราดพาสต้า เก็บในที่เย็นห่างแสง และใช้ภายในวันที่กำหนด', sentence: 'Serve extra virgin olive oil with bread for dipping and as salad dressing — store away from heat and direct light.' },

  // หมวดที่ 6 อุปกรณ์บริการอาหาร (Service Equipment)
  { name: 'ถาดเสิร์ฟอาหาร', nameEn: 'Service Tray', emoji: '🫲', use: 'ถาดสี่เหลี่ยมหรือกลมสำหรับขนส่งอาหารและอุปกรณ์จากครัวถึงโต๊ะ วางน้ำหนักให้สมดุล ของหนักอยู่ตรงกลางหรือชิดร่างกาย ยกถาดด้วยมือข้างเดียวระดับไหล่', sentence: 'Balance heavy items at the center of the service tray and carry it at shoulder height with one hand.' },
  { name: 'ถาดเครื่องดื่ม', nameEn: 'Beverage Tray', emoji: '🫴', use: 'ถาดทรงกลมขนาดเล็กถึงกลางสำหรับเสิร์ฟเครื่องดื่มโดยเฉพาะ รองด้วยผ้าคลุมถาดกันลื่น จัดแก้วให้สมดุล ยกด้วยฝ่ามือ ไม่วางถาดบนโต๊ะแขกขณะเสิร์ฟ', sentence: 'Carry the beverage tray on your palm — never set it down on the guest table when pouring drinks.' },
  { name: 'ถาดกลม', nameEn: 'Round Tray', emoji: '⭕', use: 'ถาดวงกลมมาตรฐาน ใช้เสิร์ฟทั้งอาหารและเครื่องดื่ม ยกด้วยมือเดียวรองด้วยฝ่ามือ จัดของให้หนักอยู่กึ่งกลาง ปูผ้าคลุมถาดก่อนใช้ทุกครั้ง', sentence: 'Round tray is the standard service tray — balance items centrally and use a tray cloth liner always.' },
  { name: 'ถาดสี่เหลี่ยม', nameEn: 'Rectangular Tray', emoji: '▭', use: 'ถาดทรงสี่เหลี่ยมสำหรับขนจานอาหารหลายจานพร้อมกัน วางอาหารเป็นแถวประหยัดพื้นที่ รับน้ำหนักได้มากกว่าถาดกลม ใช้สำหรับเสิร์ฟอาหารจำนวนมากหรือบุฟเฟต์', sentence: 'Rectangular tray carries multiple plates efficiently — arrange dishes in rows for maximum load stability.' },
  { name: 'เหยือกน้ำ', nameEn: 'Water Pitcher', emoji: '🥛', use: 'เหยือกแก้วหรือสแตนเลสสำหรับบรรจุน้ำเปล่า มีปากรินและที่จับ ใส่น้ำแข็งก่อนแล้วจึงเติมน้ำ เสิร์ฟน้ำจากด้านขวาของแขก รินช้าๆ ไม่ให้กระเด็น', sentence: 'Fill the water pitcher with ice first, then pour water from the guest\'s right side without splashing.' },
  { name: 'เหยือกกาแฟ', nameEn: 'Coffee Pot', emoji: '☕', use: 'เหยือกโลหะหรือเซรามิคสำหรับเสิร์ฟกาแฟร้อน มีฝาปิดและหูจับ เสิร์ฟจากด้านขวาของแขก รินช้าๆ ไม่เต็มเกินปาก อุณหภูมิกาแฟร้อนควรอยู่ที่ 85–90°C', sentence: 'Pour hot coffee at 85–90°C from the guest\'s right side — fill the cup two-thirds and avoid overfilling.' },
  { name: 'กาน้ำชา', nameEn: 'Tea Pot', emoji: '🫖', use: 'กาเซรามิคหรือแก้วสำหรับชงชา ใส่น้ำร้อน 90–95°C แล้วจุ่มถุงชาหรือกรองใบชา ทิ้งไว้ 3–5 นาที เสิร์ฟพร้อมชุดชาบนถาด วางบน Underplate กันร้อนโต๊ะ', sentence: 'Pre-warm the teapot, steep tea for 3–5 minutes at 90–95°C, and serve on a tray with a trivet to protect the table.' },
  { name: 'ถังน้ำแข็ง', nameEn: 'Ice Bucket', emoji: '🧊', use: 'ถังโลหะหรือพลาสติกสำหรับแช่ขวดไวน์หรือแชมเปญ ใส่น้ำแข็งประมาณ 2/3 ของถัง เติมน้ำเย็นเล็กน้อยให้เย็นเร็ว วางบน Stand ข้างโต๊ะแขก เช็ดขวดก่อนรินเสมอ', sentence: 'Fill ice bucket two-thirds with ice and water — place it on a stand beside the table and wipe the bottle before pouring.' },
  { name: 'คีมคีบน้ำแข็ง', nameEn: 'Ice Tong', emoji: '🦾', use: 'คีมสแตนเลสสำหรับหยิบน้ำแข็งใส่แก้วอย่างถูกสุขอนามัย ห้ามใช้มือหยิบน้ำแข็งโดยตรง บีบคีมหยิบน้ำแข็ง 1–2 ก้อน แล้วใส่แก้วก่อนเทเครื่องดื่มเสมอ', sentence: 'Always use ice tongs to handle ice hygienically — never use bare hands to touch ice.' },
  { name: 'ที่เปิดไวน์', nameEn: 'Wine Opener', emoji: '🔑', use: 'อุปกรณ์แบบ Waiter\'s Friend มีใบมีด เกลียว และที่พัก ขั้นตอน: ตัดฟอยล์ → เจาะเกลียวตรงกลาง → พักที่ขอบปากขวด → ดึงจุก → เช็ดปากขวดก่อนรินเสิร์ฟ', sentence: 'Use the waiter\'s corkscrew: cut the foil, insert the worm, lever on the rim, and extract the cork smoothly.' },

  // หมวดที่ 7 อุปกรณ์สำหรับบริการไวน์และเครื่องดื่ม (Beverage Equipment)
  { name: 'ตะกร้าไวน์', nameEn: 'Wine Basket', emoji: '🧺', use: 'ตะกร้าหวายหรือโลหะสำหรับวางขวดไวน์แดงวินเทจในแนวนอน ป้องกันการสะเทือนตะกอนไวน์ เสิร์ฟขวดไวน์วินเทจในตะกร้าเสมอเพื่อแสดงความเป็นมืออาชีพ', sentence: 'Wine basket keeps vintage red wine horizontal to prevent disturbing the sediment — a sign of professional service.' },
  { name: 'ถังแช่ไวน์', nameEn: 'Wine Cooler', emoji: '🍾', use: 'ถังสแตนเลสสำหรับแช่ไวน์ขาว แชมเปญ หรือโรเซ่ให้เย็น ใส่น้ำแข็งผสมน้ำเย็น วางบน Stand ข้างโต๊ะแขก เช็ดขวดด้วยผ้าทุกครั้งก่อนรินไวน์', sentence: 'Wine cooler chills white wine and champagne — wipe the bottle dry with a cloth before presenting and pouring.' },
  { name: 'จุกปิดขวดไวน์', nameEn: 'Wine Stopper', emoji: '🔌', use: 'อุปกรณ์อุดปิดปากขวดไวน์ที่เปิดแล้ว ช่วยรักษาความสดและป้องกันออกซิเจนเข้า เสียบจุกให้แน่นทันทีหลังเทไวน์แล้ว เก็บขวดในตู้เย็นหรือที่เย็น ใช้ภายใน 2–3 วัน', sentence: 'Insert the wine stopper firmly after pouring — refrigerate and consume the remaining wine within 2–3 days.' },
  { name: 'เครื่องรินไวน์', nameEn: 'Wine Pourer', emoji: '🍷', use: 'อุปกรณ์เสียบปากขวดไวน์ช่วยรินได้สม่ำเสมอและป้องกันหยดเลอะผ้าปูโต๊ะ ใช้สำหรับรินไวน์ที่บาร์หรือที่โต๊ะแขก เลือกรุ่นที่มีที่ดักหยด (Drip Stop) เสมอ', sentence: 'Wine pourer controls the flow and prevents drips — choose a drip-stop model for professional table service.' },
  { name: 'ที่เปิดขวด', nameEn: 'Bottle Opener', emoji: '🗝️', use: 'อุปกรณ์โลหะสำหรับเปิดฝาขวดเบียร์หรือโซดา วางขอบที่เปิดใต้ฝา กดลงพร้อมยกขึ้นฝาจะเปิด พนักงานบาร์ควรพกติดตัวเสมอ หลังใช้เช็ดทำความสะอาดทุกครั้ง', sentence: 'Hook the bottle opener under the cap edge, then press down and lever up to pop it open cleanly.' },
  { name: 'ที่เปิดไวน์แบบเกลียว', nameEn: 'Corkscrew', emoji: '🔩', use: 'อุปกรณ์เกลียวสำหรับถอดจุกคอร์กขวดไวน์ วางจุดกลาง หมุนเกลียวลงตรงกลางจุก ดึงจุกขึ้นช้าๆ อย่าให้จุกหัก ถ้าจุกขาดให้ใช้ Waiter\'s Friend ช่วย', sentence: 'Center the worm on the cork, twist slowly, and pull straight up to extract without breaking the cork.' },

  // หมวดที่ 8 อุปกรณ์ Gueridon (การบริการด้วยรถเข็น)
  { name: 'รถเข็นบริการ', nameEn: 'Gueridon Trolley', emoji: '🛒', use: 'รถเข็นสองชั้นสำหรับเตรียมและปรุงอาหารต่อหน้าลูกค้า เป็นการบริการระดับสูงสุด (Gueridon Service) ชั้นบน: เตรียมอาหาร ชั้นล่าง: วางอุปกรณ์สำรอง ต้องผ่านการฝึกก่อนใช้', sentence: 'Gueridon trolley enables tableside cooking — upper shelf for preparation, lower shelf for equipment and supplies.' },
  { name: 'เตาแอลกอฮอล์', nameEn: 'Spirit Lamp', emoji: '🔥', use: 'เตาบรรจุแอลกอฮอล์สำหรับให้ความร้อนบนรถ Gueridon ปรับระดับไฟด้วยฝาปิดเปลือก ระวังอย่าให้แอลกอฮอล์หกขณะบรรจุ ปิดฝาดับไฟเมื่อเสร็จงาน ห้ามเป่าดับ', sentence: 'Adjust the spirit lamp flame with the cover — never blow it out; always extinguish by closing the cap.' },
  { name: 'กระทะฟลอมเบ', nameEn: 'Flambé Pan', emoji: '🍳', use: 'กระทะสแตนเลสก้านยาวสำหรับทำอาหาร Flambé ต่อหน้าลูกค้า เช่น Crepe Suzette หรือ Banana Foster ราดเหล้าแล้วจุดไฟ เอียงกระทะออกจากตัวและแขกเพื่อความปลอดภัย', sentence: 'Tilt the flambé pan away from guests before igniting the spirit — keep a fire blanket nearby as a precaution.' },
  { name: 'เขียงเตรียมอาหาร', nameEn: 'Cutting Board', emoji: '🪵', use: 'เขียงไม้หรือพลาสติกสำหรับแล่เนื้อ หั่นผักบนรถ Gueridon ใช้สีเขียงตามมาตรฐาน HACCP: แดง=เนื้อแดง, เหลือง=สัตว์ปีก, เขียว=ผัก, น้ำเงิน=อาหารทะเล, ขาว=ขนมปัง', sentence: 'Follow HACCP color-coded boards: red for meat, yellow for poultry, green for vegetables, blue for seafood.' },
  { name: 'มีดเชฟ', nameEn: "Chef's Knife", emoji: '🔪', use: 'มีดทำครัวอเนกประสงค์ใบยาว 20–25 ซม. ใช้สับ หั่น แล่ และตัด จับด้วยมือถนัดโดยนิ้วโป้งและนิ้วชี้หนีบที่โคนใบมีด มืออีกข้างงอนิ้วเป็นก้ามปูกันบาด', sentence: "Grip the chef's knife at the bolster with thumb and forefinger — curl the guiding hand into a claw for safety." },
  { name: 'คีมคีบอาหารบริการ', nameEn: 'Serving Tong', emoji: '🥢', use: 'คีมสแตนเลสสำหรับหยิบและถ่ายอาหารจากถาดเสิร์ฟลงจานแขก ใช้แบบ Silver Service: ช้อน+ส้อมคีบอาหาร หรือคีมสปริง เสิร์ฟจากซ้ายของแขกเสมอ', sentence: 'In Silver Service, use spoon and fork together in one hand as tongs — serve from the guest\'s left side.' },

  // หมวดที่ 9 อุปกรณ์จัดโต๊ะ (Table Setting Accessories)
  { name: 'เชิงเทียน', nameEn: 'Candle Holder', emoji: '🕯️', use: 'ฐานรองเทียนสำหรับวางกลางโต๊ะอาหาร ความสูงต้องไม่บดบังสายตาแขก (ไม่เกิน 30 ซม.) จุดเทียนก่อนแขกมา ดูแลไม่ให้ไขเทียนหยดบนโต๊ะหรือผ้าปูโต๊ะ', sentence: 'Candle holder must not exceed 30 cm height to preserve eye contact between guests — light before seating.' },
  { name: 'แจกันดอกไม้', nameEn: 'Flower Vase', emoji: '💐', use: 'แจกันสำหรับวางดอกไม้ตกแต่งโต๊ะ ต้องสะอาดและดอกไม้สด ความสูงต้องไม่สูงเกินกว่าระดับตาของผู้นั่ง เปลี่ยนน้ำในแจกันทุกวัน ตัดก้านดอกไม้ทุก 2 วัน', sentence: 'Flower centerpieces must not obstruct sightlines — change water daily and trim stems every 2 days for freshness.' },
  { name: 'ป้ายหมายเลขโต๊ะ', nameEn: 'Table Number', emoji: '🔢', use: 'ป้ายระบุหมายเลขโต๊ะสำหรับสื่อสารระหว่างพนักงาน ควรมองเห็นชัดจากทางเข้าห้องอาหาร วางไว้ตำแหน่งกึ่งกลางโต๊ะ ช่วยให้การส่งอาหารถูกโต๊ะและรวดเร็ว', sentence: 'Table numbers identify guest covers — position them visibly at the center so servers can quickly locate orders.' },
  { name: 'การ์ดเมนู', nameEn: 'Menu Card', emoji: '📜', use: 'รายการอาหารและเครื่องดื่มทั้งหมด วางบนจานหรือส่งด้วยมือทั้งสองข้างจากขวาของแขก อ่านเมนูให้แขกฟังหากต้องการ แนะนำเมนูพิเศษประจำวัน (Daily Special) เสมอ', sentence: 'Present the menu with both hands from the guest\'s right — always recommend the chef\'s daily specials.' },
  { name: 'แผ่นจานรอง', nameEn: 'Charger Plate', emoji: '📀', use: 'จานตกแต่งขนาดใหญ่ 30–33 ซม. วางบนโต๊ะก่อนแขกมาถึง ไม่ใส่อาหารโดยตรง วางจานอาหารซ้อนบน เก็บออกพร้อมจานก่อนเสิร์ฟของหวานหรือหลังมื้ออาหาร', sentence: 'Charger plate is decorative — place it before guests arrive and remove it when serving the dessert course.' },
  { name: 'ที่รองแก้ว', nameEn: 'Coaster', emoji: '🪨', use: 'แผ่นรองกลมสำหรับวางใต้แก้วเครื่องดื่มเย็น ป้องกันน้ำที่เกิดจากการควบแน่น (Condensation) ทำให้โต๊ะเปียกหรือเสียหาย วางก่อนเสิร์ฟเครื่องดื่มเย็นเสมอ', sentence: 'Place a coaster under cold drink glasses to protect the table from condensation rings and water damage.' },

  // หมวดที่ 10 อุปกรณ์สถานีบริการ (Side Station Equipment)
  { name: 'ตู้เก็บอุปกรณ์', nameEn: 'Sideboard', emoji: '🗄️', use: 'ตู้ไม้หรือสแตนเลสสำหรับเก็บสำรองอุปกรณ์บริการ เช่น ช้อนส้อม ผ้าเช็ดปาก แก้ว เมนู จัดเป็นระเบียบแยกหมวดหมู่ เติมของสำรองก่อนเปิดบริการทุกวัน', sentence: 'Sideboard stores reserve service supplies — organize by category and fully restock before each service begins.' },
  { name: 'ถังเก็บช้อนส้อม', nameEn: 'Cutlery Holder', emoji: '🫙', use: 'ภาชนะทรงกระบอกสำหรับจัดเก็บช้อน ส้อม และมีดแยกประเภท วางใน Sideboard จัดหัวช้อนขึ้นเพื่อสุขอนามัย เก็บเฉพาะอุปกรณ์ที่ผ่านการขัดเงาแล้วเท่านั้น', sentence: 'Store polished cutlery handle-up in the holder — separate by type and keep only service-ready pieces inside.' },
  { name: 'ถังขยะบริการ', nameEn: 'Waste Bin', emoji: '🗑️', use: 'ถังขยะขนาดเล็กสำหรับพนักงานทิ้งเศษอาหาร กระดาษ หรือวัสดุใช้แล้วขณะบริการ ต้องซ่อนไว้ภายในตู้ Side Station ห้ามให้แขกเห็น เปลี่ยนถุงขยะทุกรอบบริการ', sentence: 'Waste bin must be concealed inside the side station — never visible to guests, change the liner every shift.' },
  { name: 'ถังเก็บน้ำแข็ง', nameEn: 'Ice Bin', emoji: '🧊', use: 'ถังฉนวนกันความร้อนสำหรับเก็บน้ำแข็งสำรองที่สถานีบริการ เติมน้ำแข็งก่อนเปิดบริการ ล้างถังทุกวันป้องกันแบคทีเรีย ใช้คีมน้ำแข็งหยิบทุกครั้งห้ามใช้มือโดยตรง', sentence: 'Ice bin stores reserve service ice — sanitize daily and always use tongs, never bare hands, to retrieve ice.' },
  { name: 'ถาดเก็บจาน', nameEn: 'Plate Rack', emoji: '🍽️', use: 'ชั้นหรือถาดสำหรับจัดเก็บจานซ้อนกันเป็นระเบียบ วางจานสะอาดที่ขัดเงาแล้วเท่านั้น ซ้อนจานตามประเภทและขนาด เก็บในที่สะอาดห่างจากพื้น', sentence: 'Stack only clean, polished plates in the rack by type and size — keep them off the floor for hygiene.' },
  { name: 'ตะกร้าเก็บผ้า', nameEn: 'Linen Basket', emoji: '🧺', use: 'ตะกร้าสำหรับรวบรวมผ้าเช็ดปาก ผ้าปูโต๊ะ และผ้าอื่นๆ ที่ใช้แล้ว ส่งซักและรีดก่อนนำมาใช้ใหม่ ห้ามนำผ้าที่ใช้แล้วมาใช้ซ้ำในรอบเดิมเด็ดขาด', sentence: 'Collect all used linens in the basket for laundering — never reuse napkins or cloths within the same service shift.' }
]'''

with open(FILE_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

# Find and replace the defaultEquipment block
start_marker = 'const defaultEquipment: Equipment[] = ['
end_marker = ']\n\nconst aiResults'

start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print(f"ERROR: Could not find markers. start={start_idx}, end={end_idx}")
    exit(1)

# The end should include the ']' of defaultEquipment
actual_end = end_idx + 1  # include the ']'

new_content = content[:start_idx] + NEW_EQUIPMENT + '\n\n' + content[actual_end + 1:]

with open(FILE_PATH, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"SUCCESS: Updated defaultEquipment in {FILE_PATH}")
print(f"  Original block: chars {start_idx}–{actual_end}")
print(f"  New equipment items: {NEW_EQUIPMENT.count('nameEn:')}")
